add Mega Menus to Pro Features
BoldGrid/crio pull request #8
Opened 2023-01-18 19:03 UTC by jamesros161

Resolves #5

Testing Instructions:

Activate theme without Crio Pro installed.
Ensure the number '1' is shown under Crio > Pro Features.
View the Pro Features page, and ensure the first item shown is the 'Mega Menu' Card and that it has the 'New' banner.
Leave the page, or refresh, and ensure the 'New' banner disappears and that the '1' is no longer shown under Crio > Pro Features.

2023-01-18 19:58 UTC, avonville approved these changes

2023-01-18 20:00 UTC, avonville requested changes

2023-01-18 20:00 UTC, avonville commented on src/includes/configs/pro-feature-cards.config.php
> +	'mega-menus'          => array(
spacing is off for =>

2023-01-19 21:06 UTC, nicolepaschen commented
looks good ty!

2023-02-06 21:06 UTC, merged

2023-02-07 18:55 UTC, nicolepaschen commented
beta1 looks good

2023-02-13 19:26 UTC, nicolepaschen commented
RC1 looks good